FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
# Default is Developer Edition
ENV MSSQL_PID=Developer

# Copy the SQL file to a directory in the container
COPY ./src/main/resources/createdb.sql /usr/src/app/createdb.sql

# Run the SQL script after SQL Server starts
CMD /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 20 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -i /usr/src/app/createdb.sql"

