# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "prod", "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Create .env file from secrets
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
        echo "GOOGLE_LINK_GET_TOKEN=${{ secrets.GOOGLE_LINK_GET_TOKEN }}" >> .env
        echo "GOOGLE_LINK_GET_USER_INFO=${{ secrets.GOOGLE_LINK_GET_USER_INFO }}" >> .env
        echo "GOOGLE_GRANT_TYPE=${{ secrets.GOOGLE_GRANT_TYPE }}" >> .env

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        GOOGLE_LINK_GET_TOKEN: ${{ secrets.GOOGLE_LINK_GET_TOKEN }}
        GOOGLE_LINK_GET_USER_INFO: ${{ secrets.GOOGLE_LINK_GET_USER_INFO }}
        GOOGLE_GRANT_TYPE: ${{ secrets.GOOGLE_GRANT_TYPE }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
